"""Generate the categorical node ramps for design.css and ui/graph.py.

Per the design addendum (design_handoff_ingredient_foundry/ADDENDUM.md): the five
node hues keep their identity — their OKLCH *hue angle* — but are re-anchored to one
shared lightness and chroma so no hue reads louder than its neighbours. Ramps 100-900
then walk a single lightness scale with chroma eased down at both ends.

Colour in these graphs is meaning, not decoration, so the output is emitted as hex:
vis-network paints to a canvas and the values are read by both CSS and Python.

Run: py -3.11 scripts/gen_palette.py            # prints CSS + Python blocks
"""

from __future__ import annotations

import math

# Our five hues — the ones already carrying meaning in the graphs. Only their hue
# angle survives; lightness and chroma are normalised below.
SOURCE_HUES = {
    "ingredient": "#0E7C5A",   # green
    "technique":  "#1F6FC4",   # blue
    "component":  "#6B4C8A",   # purple
    "filler":     "#A5640A",   # amber  (also flavour routes)
    "destination": "#B23B2E",  # red
}

BASE_L = 0.62   # shared lightness for the 500 step
BASE_C = 0.11   # shared chroma for the 500 step

STEPS = [100, 200, 300, 400, 500, 600, 700, 800, 900]
L_SCALE = [0.97, 0.93, 0.86, 0.76, 0.62, 0.52, 0.42, 0.32, 0.24]
# Chroma eases off at both ends so the palest and darkest steps stay neutral-ish
# rather than turning into saturated pastels and muds.
C_SCALE = [0.18, 0.32, 0.52, 0.78, 1.00, 0.98, 0.88, 0.72, 0.55]


# ---- colour conversion (sRGB <-> OKLab/OKLCH) ------------------------------

def _srgb_to_linear(c: float) -> float:
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def _linear_to_srgb(c: float) -> float:
    return 12.92 * c if c <= 0.0031308 else 1.055 * (c ** (1 / 2.4)) - 0.055


def hex_to_oklch(hex_color: str) -> tuple[float, float, float]:
    r, g, b = (_srgb_to_linear(int(hex_color[i:i + 2], 16) / 255)
               for i in (1, 3, 5))
    l = 0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b
    m = 0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b
    s = 0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b
    l_, m_, s_ = (v ** (1 / 3) if v > 0 else -((-v) ** (1 / 3)) for v in (l, m, s))
    L = 0.2104542553 * l_ + 0.7936177850 * m_ - 0.0040720468 * s_
    a = 1.9779984951 * l_ - 2.4285922050 * m_ + 0.4505937099 * s_
    bb = 0.0259040371 * l_ + 0.7827717662 * m_ - 0.8086757660 * s_
    return L, math.hypot(a, bb), math.degrees(math.atan2(bb, a)) % 360


def oklch_to_rgb(L: float, C: float, H: float) -> tuple[float, float, float]:
    """Return unclamped linear-light sRGB — out-of-gamut shows as <0 or >1."""
    a = C * math.cos(math.radians(H))
    b = C * math.sin(math.radians(H))
    l_ = L + 0.3963377774 * a + 0.2158037573 * b
    m_ = L - 0.1055613458 * a - 0.0638541728 * b
    s_ = L - 0.0894841775 * a - 1.2914855480 * b
    l, m, s = l_ ** 3, m_ ** 3, s_ ** 3
    return (
        4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
        -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
        -0.0041960863 * l - 0.7034186147 * m + 1.7076147010 * s,
    )


def oklch_to_hex(L: float, C: float, H: float) -> str:
    """Clip into sRGB by walking chroma down — preserves hue and lightness."""
    while C > 0:
        rgb = oklch_to_rgb(L, C, H)
        if all(-1e-4 <= v <= 1 + 1e-4 for v in rgb):
            break
        C -= 0.002
    r, g, b = (min(1.0, max(0.0, _linear_to_srgb(min(1.0, max(0.0, v)))))
               for v in oklch_to_rgb(L, C, H))
    return "#{:02X}{:02X}{:02X}".format(*(round(v * 255) for v in (r, g, b)))


# ---- ramp construction -----------------------------------------------------

def ramp(hue: float) -> dict[int, str]:
    return {
        step: oklch_to_hex(L_SCALE[i], BASE_C * C_SCALE[i], hue)
        for i, step in enumerate(STEPS)
    }


def relative_luminance(hex_color: str) -> float:
    r, g, b = (_srgb_to_linear(int(hex_color[i:i + 2], 16) / 255)
               for i in (1, 3, 5))
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def contrast(a: str, b: str) -> float:
    la, lb = relative_luminance(a), relative_luminance(b)
    hi, lo = max(la, lb), min(la, lb)
    return (hi + 0.05) / (lo + 0.05)


def build() -> dict[str, dict[int, str]]:
    return {name: ramp(hex_to_oklch(src)[2]) for name, src in SOURCE_HUES.items()}


def main() -> None:
    ramps = build()

    print("/* ---- categorical node ramps — generated by scripts/gen_palette.py ---- */")
    for name, r in ramps.items():
        for step in STEPS:
            print(f"  --{name}-{step}: {r[step]};")
        print()

    print("# graph.py node colours (the 500 step of each ramp)")
    print("_COLORS = {")
    for name, r in ramps.items():
        print(f'    "{name}": "{r[500]}",')
    print("}")

    print("\n# sanity — contrast of the text steps on their own tinted fills")
    for name, r in ramps.items():
        print(f"  {name:12} 700-on-200 {contrast(r[700], r[200]):.2f}  "
              f"800-on-100 {contrast(r[800], r[100]):.2f}  "
              f"500-on-bg  {contrast(r[500], '#F4F2EC'):.2f}")


if __name__ == "__main__":
    main()
